version: '3.1'
services:

  redis:
    image: 'redis:7.2'
    networks:
      - hmpps
    container_name: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'

  app:
    build:
      context: .
      args:
        BUILD_NUMBER: "1.0.0"
        GIT_REF: "a1b2c3"
        GIT_BRANCH: main
    networks:
      - hmpps
    depends_on: [redis]
    ports:
      - "3000:3000"
    environment:
      - PRODUCT_ID=UNASSIGNED
      - REDIS_HOST=redis
      - HMPPS_AUTH_EXTERNAL_URL=http://localhost:9090/auth
      - HMPPS_AUTH_URL=http://hmpps-auth:8080/auth
      # These will need to match new creds in the seed auth service auth
      - AUTH_CODE_CLIENT_ID=client-id
      - AUTH_CODE_CLIENT_SECRET=client-secret
      - CLIENT_CREDS_CLIENT_ID=system-client-id
      - CLIENT_CREDS_CLIENT_SECRET=system-client-secret
      - SESSION_SECRET=somesecretvalue
      - TOKEN_VERIFICATION_API_URL=http://hmpps-auth:8080/auth
      - TOKEN_VERIFICATION_ENABLED=false
      - INGRESS_URL=http://localhost:3000
      - SERVICE_LIST_ENV=dev

volumes:
  strapi-data:

networks:
  hmpps:
