// eslint-disable-next-line no-shadow,import/prefer-default-export
export enum AuditEvent {
  VIEW_REPORT_LIST_ATTEMPT = 'VIEW_REPORT_LIST_ATTEMPT',
  VIEW_REPORT_LIST_FAILURE = 'VIEW_REPORT_LIST_FAILURE',
  DOWNLOAD_REPORT_ATTEMPT = 'DOWNLOAD_REPORT_ATTEMPT',
  DOWNLOAD_REPORT_FAILURE = 'DOWNLOAD_REPORT_FAILURE',

  REQUEST_REPORT_ATTEMPT = 'REQUEST_REPORT_ATTEMPT',
  REQUEST_REPORT_FAILURE = 'REQUEST_REPORT_FAILURE',

  VIEW_ADMIN_REPORTS_ATTEMPT = 'VIEW_ADMIN_REPORTS_ATTEMPT',
  VIEW_ADMIN_REPORT_DETAIL_ATTEMPT = 'VIEW_ADMIN_REPORT_DETAIL_ATTEMPT',
  VIEW_ADMIN_HEALTH_ATTEMPT = 'VIEW_ADMIN_HEALTH_ATTEMPT',
  RESTART_REPORT_ATTEMPT = 'RESTART_REPORT_ATTEMPT',
}
