---
generic-service:
  nameOverride: hmpps-subject-access-request-ui
  serviceAccountName: hmpps-subject-access-request
  productId: 	DPS083

  replicaCount: 4

  image:
    repository: ghcr.io/ministryofjustice/hmpps-subject-access-request-ui
    tag: app_version    # override at deployment time
    port: 3000

  ingress:
    enabled: true
    host: app-hostname.local    # override per environment
    tlsSecretName: hmpps-subject-access-request-ui-cert

  livenessProbe:
    httpGet:
      path: /ping

  readinessProbe:
    httpGet:
      path: /ping

  custommetrics:
    enabled: true
    scrapeInterval: 15s
    metricsPath: /metrics
    metricsPort: 3001

  # Environment variables to load into the deployment
  env:
    NODE_ENV: "production"
    REDIS_TLS_ENABLED: "true"
    TOKEN_VERIFICATION_ENABLED: "true"
    AUDIT_SQS_REGION: "eu-west-2"
    AUDIT_SERVICE_NAME: "hmpps-subject-access-request"

  # Pre-existing kubernetes secrets to load as environment variables in the deployment.
  # namespace_secrets:
  #   [name of kubernetes secret]:
  #     [name of environment variable as seen by app]: [key of kubernetes secret to load]

  namespace_secrets:
    hmpps-subject-access-request-ui:
      API_CLIENT_ID: "API_CLIENT_ID"
      API_CLIENT_SECRET: "API_CLIENT_SECRET"
      SYSTEM_CLIENT_ID: "SYSTEM_CLIENT_ID"
      SYSTEM_CLIENT_SECRET: "SYSTEM_CLIENT_SECRET"
      SESSION_SECRET: "SESSION_SECRET"
    hmpps-subject-access-request-ui-application-insights:
      APPLICATIONINSIGHTS_CONNECTION_STRING: "APPLICATIONINSIGHTS_CONNECTION_STRING"
    hmpps-subject-access-request-ui-auth-code:
      AUTH_CODE_CLIENT_ID: "AUTH_CODE_CLIENT_ID"
      AUTH_CODE_CLIENT_SECRET: "AUTH_CODE_CLIENT_SECRET"
    hmpps-subject-access-request-ui-client_creds:
      CLIENT_CREDS_CLIENT_ID: "CLIENT_CREDS_CLIENT_ID"
      CLIENT_CREDS_CLIENT_SECRET: "CLIENT_CREDS_CLIENT_SECRET"
    sqs-hmpps-audit-secret:
      AUDIT_SQS_QUEUE_URL: "sqs_queue_url"
      AUDIT_SQS_QUEUE_NAME: "sqs_queue_name"
    elasticache-redis:
      REDIS_HOST: "primary_endpoint_address"
      REDIS_AUTH_TOKEN: "auth_token"

  allowlist:
    groups:
      - digital_staff_and_mojo
      - moj_cloud_platform

generic-prometheus-alerts:
  targetApplication: hmpps-subject-access-request-ui
