---
# Per environment values which override defaults in hmpps-subject-access-request-ui/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: subject-access-request-dev.hmpps.service.justice.gov.uk

  env:
    INGRESS_URL: "https://subject-access-request-dev.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-dev.prison.service.justice.gov.uk"
    SERVICE_CATALOGUE_URL: "https://service-catalogue.hmpps.service.justice.gov.uk/v1"
    SERVICE_CATALOGUE_ENV: "dev"
    ENVIRONMENT_NAME: DEV
    SAR_ENDPOINT_URL: "https://subject-access-request-api-dev.hmpps.service.justice.gov.uk"

generic-prometheus-alerts:
  alertSeverity: digital-prison-service-dev
