---
# Per environment values which override defaults in hmpps-subject-access-request-ui/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: subject-access-request-dev.hmpps.service.justice.gov.uk

  env:
    INGRESS_URL: "https://subject-access-request-dev.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-dev.prison.service.justice.gov.uk"
    SERVICE_LIST_ENV: "dev"
    ENVIRONMENT_NAME: DEV
    SAR_ENDPOINT_URL: "https://subject-access-request-api-dev.hmpps.service.justice.gov.uk"

  scheduledDowntime:
    enabled: true
    startup: '29 6 * * 1-5' # Start at 6.29am UTC Monday-Friday
    shutdown: '49 21 * * 1-5' # Stop at 9.49pm UTC Monday-Friday

generic-prometheus-alerts:
  businessHoursOnly: true
  alertSeverity: digital-prison-service-dev
